pipeline:
  name: GoSampleGitHubRepoBuildPipeline
  identifier: GoSampleGitHubRepoBuildPipeline
  projectIdentifier: gosample
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHubGoSampleRepoConnector
        build: <+input>
  stages:
    - stage:
        name: GoSampleBuildStage
        identifier: GoSampleBuildStage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    connectorRef: account.harnessImage
                    image: gosampleimage
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
