pipeline:
  name: GoSampleGitHubRepoBuildPipeline
  identifier: GoSampleGitHubRepoBuildPipeline
  projectIdentifier: gosample
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHubGoSampleRepoConnector
        build: <+input>
  stages:
    - stage:
        name: GoSampleBuildStage
        identifier: GoSampleBuildStage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    connectorRef: DockerRegistryConnectorGosample
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: DockerRegistryConnectorGosample
                    repo: shigerusakai/dockerhub_repo_gosample
                    tags:
                      - <+pipeline.sequenceId>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
